# By default Spring configures the application to connect to an in-memory
# store with the username sa and an empty password. We override those parameters
spring:
  datasource:
    url: jdbc:h2:mem:senewebdb
    driverClassName: org.h2.Driver
    username: bocar
    password: bocar
  # Jpa/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # enable the H2 Console in browser http://localhost:port/h2-console
  h2:
    console:
      enabled: true